version: '3.7'

services:
  nacos:
    image: nacos/nacos-server:v3.0.2
    container_name: nacos
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_USER=xksms
      - MYSQL_SERVICE_PASSWORD=xksms
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=30000&socketTimeout=30000&autoReconnect=true
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN_EXPIRE_SECONDS=18000
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    volumes:
      - ./nacos-data:/home/nacos/data
      - ./nacos-logs:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    restart: always
    networks:
      - xksms-net

volumes:
  nacos-data:
  nacos-logs:

networks:
  xksms-net:
    external: true  # 使用已存在的网络，假设由ELK先创建