services:
  nacos:
    image: nacos/nacos-server:v3.0.2
    container_name: nacos
    environment:
      - MODE=standalone
      - NACOS_SERVER_IP=192.168.2.10
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=xksmsxksms
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=30000&socketTimeout=30000&autoReconnect=true
    volumes:
      - ./nacos-data:/home/nacos/data
      - ./nacos-logs:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
      - "8080:8080"
    restart: always
    networks:
      - xksms-net

volumes:
  nacos-data:
  nacos-logs:

networks:
  xksms-net:
    external: true  # 使用已存在的网络，假设由ELK先创建