<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xksms</groupId>
        <artifactId>xksms-cloud</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>xksms-common</artifactId>
    <packaging>pom</packaging>
    <version>${revision}</version>
    <name>${project.artifactId}</name>
    <description>xksms-cloud 公共模块父 POM，包含核心工具类、枚举、常量等</description>

    <modules>
        <module>xksms-common-core</module>
    </modules>
</project>
