version: '3.7'

services:
  skywalking-oap:
    image: apache/skywalking-oap-server:10.2.0-java17
    environment:
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
      - SW_HEALTH_CHECKER=default
      - SW_HEALTH_CHECKER_INTERVAL_SECONDS=5
      - SW_TELEMETRY=prometheus
    ports:
      - "11800:11800"
      - "12800:12800"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:12800/healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - xksms-net

  skywalking-ui:
    image: apache/skywalking-ui:10.2.0-java17
    container_name: skywalking-ui
    environment:
      - SW_OAP_ADDRESS=http://skywalking-oap:12800
    ports:
      - "18080:8080"
    depends_on:
      skywalking-oap:
        condition: service_healthy
    networks:
      - xksms-net

networks:
  xksms-net:
    external: true
