<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xksms</groupId>
        <artifactId>xksms-cloud</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>xksms-platform</artifactId>
    <packaging>pom</packaging>
    <version>${revision}</version>
    <name>${project.artifactId}</name>
    <description>平台层: 存放所有基础核心服务</description>

    <modules>
        <module>xksms-user</module>
        <module>xksms-system</module>
        <!--        <module>xksms-notify</module>-->
    </modules>

</project>