version: '3'

services:
  prometheus:
    image: prom/prometheus:v3.4.2
    container_name: prometheus3.4.2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - xksms-net
    restart: always

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - xksms-net
    restart: always
volumes:
  grafana-data:

networks:
  xksms-net:
    external: true